services:
  - type: web
    name: ps99bet-backend
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OWNER_DISCORD_ID
        sync: false
      - key: BJ_WEBHOOK
        sync: false
